apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-staging
spec:
  secretName: wildcard-cert-staging
  commonName: "*.darrellandranae.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  dnsNames:
  - "*.darrellandranae.com"
