apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cert-mgr-config/
    repoURL: git@github.com:DarrellTang/argocd-k3s.git
    targetRevision: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
