apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: networking/coredns/
    repoURL: git@github.com:DarrellTang/argocd-k3s.git
    targetRevision: HEAD
