apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  destination:
    namespace: networking
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: networking/coredns
    repoURL: git@gitlab.com:darrelltang/flux-k3s.git
    targetRevision: HEAD
