apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: coredns/
    repoURL: git@github.com:DarrellTang/argocd-k3s.git
    targetRevision: argocd-migration
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
