apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: nginx-ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nginx-ingress
    helm:
      parameters:
      - name: jiva.enabled
        value: "true"
      - name: jiva.replicas
        value: "1"
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.2.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
