apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-config
  namespace: argocd
spec:
  destination:
    namespace: openebs
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openebs-config/
    repoURL: git@github.com:DarrellTang/argocd-k3s.git
    targetRevision: feature/openebs
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
