apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: magicmirror
  labels:
    app: magicmirror
spec:
  selector:
    matchLabels:
      app: magicmirror
  endpoints:
  - port: http
