---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: '*'
  install: {}
  interval: 5m0s
  valuesFrom:
      valuesKey: custom-values.yaml
#   kube-state-metrics:
#     image:
#       repository: eddiezane/kube-state-metrics
#       tag: v1.9.7
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheus:
      prometheusSpec:
        retention: 3d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
    prometheusOperator:
      admissionWebhooks:
        enabled: false
      tls:
        enabled: false

