---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      version: '*'
      interval: 1m
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      valuesKey: custom-values.yaml
      name: custom-values
