apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-zones
  namespace: networking
data:
    db.tang.local: |
      $TTL  30M
      @   IN  SOA  ns1.tang.local.  tang.local.  (
                      2021100700  ; Serial
                      4H          ; Refresh
                      1H          ; Retry
                      7D          ; Expire
                      4H )        ; Negative Cache TTL
          IN  NS  ns1
  
      pihole.tang.local.        IN  A  10.0.0.230 
      grafana.tang.local.       IN  A  10.0.0.230 
      prometheus.tang.local.    IN  A  10.0.0.230 
      alertmanager.tang.local.  IN  A  10.0.0.230 
      magicmirror.tang.local.   IN  A  10.0.0.230 
      blackbox.tang.local.      IN  A  10.0.0.230 
      argocd.tang.local.        IN  A  10.0.0.230 
