---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
      version: '*'
  interval: 5m0s
  suspend: true
  values:
    DNS1: 8.8.8.8
    DNS2: 8.8.4.4
    admin:
      existingSecret: pihole-admin
      passwordKey: password
    adminPassword: admin
    customVolumes:
      config: {}
      enabled: false
    dnsmasq:
      customCnameEntries: []
      customDnsEntries:
      - address=/pihole.tang.local/10.0.0.230
      - address=/grafana.tang.local/10.0.0.230
      - address=/alertmanager.tang.local/10.0.0.230
      - address=/prometheus.tang.local/10.0.0.230
    extraEnvVars:
      TZ: America/Los_Angeles
    hostname: pihole
    image:
      pullPolicy: IfNotPresent
      repository: pihole/pihole
      tag: v5.8.1
    maxSurge: 1
    maxUnavailable: 1
    monitoring:
      podMonitor:
        enabled: false
      sidecar:
        enabled: false
        image:
          pullPolicy: IfNotPresent
          repository: ekofr/pihole-exporter
          tag: 0.0.10
        port: 9617
        resources:
          limits:
            memory: 128Mi
    persistentVolumeClaim:
      accessModes:
      - ReadWriteOnce
      enabled: false
      size: 500Mi
    podDnsConfig:
      enabled: true
      nameservers:
      - 127.0.0.1
      - 8.8.8.8
      policy: None
    probes:
      liveness:
        enabled: true
        failureThreshold: 10
        initialDelaySeconds: 60
        timeoutSeconds: 5
      readiness:
        enabled: true
        failureThreshold: 3
        initialDelaySeconds: 60
        timeoutSeconds: 5
    replicaCount: 1
    serviceDhcp:
      enabled: false
    serviceDns:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      loadBalancerIP: ""
      port: 53
      type: LoadBalancer
    serviceWeb:
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      http:
        enabled: true
        port: 80
      https:
        enabled: true
        port: 443
      loadBalancerIP: ""
      type: LoadBalancer
    strategyType: RollingUpdate

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: '*'
  interval: 5m0s
  values:
    configInline:
      address-pools:
      - addresses:
        - 10.0.0.230-10.0.0.240
        name: default
        protocol: layer2

