---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 5m0s
  url: https://github.com/MoJo2600/pihole-kubernetes/charts

