apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: '*'
  interval: 5m0s
  values:
    configInline:
      address-pools:
      - addresses:
        - 10.0.0.230-10.0.0.240
        name: default
        protocol: layer2
