apiVersion: apps/v1
kind: Deployment
metadata:
  name: fffff-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fffff-backend
  template:
    metadata:
      labels:
        app: fffff-backend
    spec:
      containers:
        - name: fffff-backend
          image: 'ghcr.io/DarrellTang/fffff-backend:'
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
          readinessProbe:
            exec:
              command:
                - nc
                - -z
                - postgres
                - "5432"
            initialDelaySeconds: 5
            timeoutSeconds: 5
