apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl-download-job
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: alpine:latest
            command: ["/bin/sh", "-c"]
            args:
            - |
              apk add curl sed
              curl -L -o /data/item.csv https://github.com/xivapi/ffxiv-datamining/raw/master/csv/Item.csv
              sed -i 1,3d /data/item.csv
            volumeMounts:
            - name: csv-volume
              mountPath: /data
          volumes:
          - name: csv-volume
            persistentVolumeClaim:
              claimName: csv-pvc
          restartPolicy: OnFailure
