apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: fffff
    app.kubernetes.io/instance: argocd
  name: fffff
  namespace: fffff
spec:
  ingressClassName: nginx
  rules:
  - host: fffff.tang.local
    http:
      paths:
      - backend:
          service:
            name: fffff
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
