apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: openebs-jiva-csi-default
  resources:
    requests:
      storage: 100Mi
